version: '2.2'

services:
  redis:
    image: redis:3.0.7
    expose:
      - "6379"

  rabbitmq:
    image: rabbitmq:3.8.2
    expose:
      - "5672"

  zookeeper:
    restart: always
    image: yfgu9nc3.mirror.aliyuncs.com/confluentinc/cp-zookeeper:latest
    ports:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    restart: always
    image: yfgu9nc3.mirror.aliyuncs.com/confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  examples:
    build: ./

    volumes:
      - ../examples:/opt/examples
      - ../event:/opt/examples/event

    command: sleep 10000000000
